use crate::layout::COL;
pub use crate::layout::shared::layout::ROW0;
use rmk::{a, df, k, types::action::KeyAction};

pub const ROW1: [KeyAction; COL] = [
    k!(Grave),
    k!(Kc1),
    k!(Kc2),
    k!(Kc3),
    k!(Kc4),
    k!(Kc5),
    k!(Kc6),
    k!(Kc7),
    k!(Kc8),
    k!(Kc9),
    k!(Kc0),
    k!(Minus),
    k!(Equal),
    k!(International3),
    k!(Backspace),
    k!(Insert),
    k!(Home),
    k!(PageUp),
    k!(NumLock),
    k!(KpSlash),
    k!(KpAsterisk),
];

pub const ROW2: [KeyAction; COL] = [
    k!(Tab),
    k!(Q),
    k!(W),
    k!(E),
    k!(R),
    k!(T),
    k!(Y),
    k!(U),
    k!(I),
    k!(O),
    k!(P),
    k!(LeftBracket),
    k!(RightBracket),
    k!(Enter),
    k!(Delete),
    k!(End),
    k!(PageDown),
    k!(Kp7),
    k!(Kp8),
    k!(Kp9),
    k!(KpPlus),
];

pub const ROW3: [KeyAction; COL] = [
    k!(CapsLock),
    k!(A),
    k!(S),
    k!(D),
    k!(F),
    k!(G),
    k!(H),
    k!(J),
    k!(K),
    k!(L),
    k!(Semicolon),
    k!(Quote),
    k!(Backslash),
    a!(No),
    a!(No),
    a!(No),
    a!(No),
    k!(Kp4),
    k!(Kp5),
    k!(Kp6),
    a!(No),
];

pub const ROW4: [KeyAction; COL] = [
    k!(LShift),
    a!(No),
    k!(Z),
    k!(X),
    k!(C),
    k!(V),
    k!(B),
    k!(N),
    k!(M),
    k!(Comma),
    k!(Dot),
    k!(Slash),
    k!(International1),
    k!(RShift),
    a!(No),
    k!(Up),
    a!(No),
    k!(Kp1),
    k!(Kp2),
    k!(Kp3),
    k!(KpEnter),
];

pub const MAC_ROW5: [KeyAction; COL] = [
    k!(LCtrl),
    k!(LAlt),
    k!(LGui),
    k!(Language2),
    a!(No),
    a!(No),
    k!(Space),
    df!(0),
    df!(1),
    k!(Language1),
    k!(RGui),
    k!(RAlt),
    k!(RCtrl),
    a!(No),
    k!(Left),
    k!(Down),
    k!(Right),
    k!(Kp0),
    k!(KpDot),
    a!(No),
    a!(No),
];
pub const WIN_ROW5: [KeyAction; COL] = [
    k!(LCtrl),
    k!(LGui),
    k!(LAlt),
    k!(International5),
    a!(No),
    df!(0),
    k!(Space),
    a!(No),
    a!(No),
    k!(International4),
    k!(RAlt),
    k!(RGui),
    k!(RCtrl),
    df!(1),
    k!(Left),
    k!(Down),
    k!(Right),
    k!(Kp0),
    k!(KpDot),
    a!(No),
    a!(No),
];
