#![expect(clippy::min_ident_chars, reason = "rmk macro names a!/k! are fixed upstream and cannot be renamed")]

use crate::layout::COL;
pub use crate::layout::shared::layout::ROW0;
use rmk::{a as act, df, k as key, types::action::KeyAction};

pub const ROW1: [KeyAction; COL] = [
    key!(Grave),
    key!(Kc1),
    key!(Kc2),
    key!(Kc3),
    key!(Kc4),
    key!(Kc5),
    key!(Kc6),
    key!(Kc7),
    key!(Kc8),
    key!(Kc9),
    key!(Kc0),
    key!(Minus),
    key!(Equal),
    key!(International3),
    key!(Backspace),
    key!(Insert),
    key!(Home),
    key!(PageUp),
    key!(NumLock),
    key!(KpSlash),
    key!(KpAsterisk),
];

pub const ROW2: [KeyAction; COL] = [
    key!(Tab),
    key!(Q),
    key!(W),
    key!(E),
    key!(R),
    key!(T),
    key!(Y),
    key!(U),
    key!(I),
    key!(O),
    key!(P),
    key!(LeftBracket),
    key!(RightBracket),
    key!(Enter),
    key!(Delete),
    key!(End),
    key!(PageDown),
    key!(Kp7),
    key!(Kp8),
    key!(Kp9),
    key!(KpPlus),
];

pub const ROW3: [KeyAction; COL] = [
    key!(CapsLock),
    key!(A),
    key!(S),
    key!(D),
    key!(F),
    key!(G),
    key!(H),
    key!(J),
    key!(K),
    key!(L),
    key!(Semicolon),
    key!(Quote),
    key!(Backslash),
    act!(No),
    act!(No),
    act!(No),
    act!(No),
    key!(Kp4),
    key!(Kp5),
    key!(Kp6),
    act!(No),
];

pub const ROW4: [KeyAction; COL] = [
    key!(LShift),
    act!(No),
    key!(Z),
    key!(X),
    key!(C),
    key!(V),
    key!(B),
    key!(N),
    key!(M),
    key!(Comma),
    key!(Dot),
    key!(Slash),
    key!(International1),
    key!(RShift),
    act!(No),
    key!(Up),
    act!(No),
    key!(Kp1),
    key!(Kp2),
    key!(Kp3),
    key!(KpEnter),
];

pub const MAC_ROW5: [KeyAction; COL] = [
    key!(LCtrl),
    key!(LAlt),
    key!(LGui),
    key!(Language2),
    act!(No),
    act!(No),
    key!(Space),
    df!(0),
    df!(1),
    key!(Language1),
    key!(RGui),
    key!(RAlt),
    key!(RCtrl),
    act!(No),
    key!(Left),
    key!(Down),
    key!(Right),
    key!(Kp0),
    key!(KpDot),
    act!(No),
    act!(No),
];
pub const WIN_ROW5: [KeyAction; COL] = [
    key!(LCtrl),
    key!(LGui),
    key!(LAlt),
    key!(International5),
    act!(No),
    df!(0),
    key!(Space),
    act!(No),
    act!(No),
    key!(International4),
    key!(RAlt),
    key!(RGui),
    key!(RCtrl),
    df!(1),
    key!(Left),
    key!(Down),
    key!(Right),
    key!(Kp0),
    key!(KpDot),
    act!(No),
    act!(No),
];
