//! Chebyshev polynomial approximation for analog hall sensor travel.
//!
//! Evaluated via Clenshaw recurrence using f32 on the Cortex-M4F FPU.
//! Division is avoided by pre-computing the reciprocal of X_HALF as a
//! constant — LLVM emits a single VMUL.F32 instead of VDIV.F32 (14 cy).
//!
//! Max error vs. exact division: 1 Q8 unit (0.004 mm).
use core::ops::{Add as _, Mul as _, Sub as _};

/// Midpoint of the valid ADC range: (3500 + 1200) / 2.
const X_MID: f32 = 2350.0_f32;

/// Reciprocal of the half-width, used in place of division.
/// 1.0 / 1150.0 in f32 — LLVM folds this to a VMUL constant at compile time.
const X_HALF_RECIP: f32 = 1.0_f32 / 1150.0_f32;

/// Chebyshev coefficients for the degree-3 approximation of the hall sensor
/// transfer curve, generated by `poly_gen/cheby.py`.
///
/// The original cubic f(x) = A + Bx + Cx² + Dx³ is re-expressed in the
/// Chebyshev basis T₀.T₃ on t ∈ \[-1, 1\], where t = (x − 2350) / 1150:
///
/// f(x) ≈ c0·T₀(t) + c1·T₁(t) + c2·T₂(t) + c3·T₃(t).
///
/// Coefficients are truncated to f32 precision from the sympy output.
const C0: f32 = 27.824_872_f32;

/// Dominant linear slope — large negative due to the inverse travel/ADC
/// relationship.
const C1: f32 = -54.576_237_f32;

/// Minor quadratic curvature correction.
const C2: f32 = -4.243_532_f32;

/// Cubic asymmetry correction at the extremes of the travel range.
const C3: f32 = -11.382_533_f32;

/// f(3121) in the Chebyshev basis, subtracted so zero-travel → delta 0.
const REF_VAL: f32 = 0.837_090_f32;

/// Minimum valid raw ADC input.
pub const VALID_RAW_MIN: u16 = 1200_u16;
/// Maximum valid raw ADC input.
pub const VALID_RAW_MAX: u16 = 3500_u16;
/// Q8 scale of the value returned by [`delta_from_ref`]./// Q exponent of the
/// delta values returned by [`delta_from_ref`].
pub const DELTA_Q: u32 = 8_u32;
/// Q exponent of the per-key scale factor stored in `KeyCalib`.
pub const SCALE_Q: i32 = 16_i32;
/// Combined right-shift when converting delta × `scale_factor` → travel.
pub const SCALE_SHIFT: u32 = DELTA_Q.saturating_add(u32::try_from(SCALE_Q).unwrap_or_default());
/// Identity scale factor for uncalibrated keys.
pub const SCALE_Q_FACTOR: i32 = 1_i32 << SCALE_Q;

/// Evaluate the degree-3 Chebyshev series at `t` via Clenshaw recurrence.
#[inline]
const fn chebyshev(raw: f32) -> f32 {
    let t2 = raw.mul(2.0_f32);
    let b3 = C3;
    let b2 = t2.mul(b3).add(C2);
    let b1 = t2.mul(b2).add(C1).sub(b3);
    raw.mul(b1).add(C0).sub(b2)
}

/// Returns (f(raw) − f(3121)) as a Q8 fixed-point value (scaled by 256).
#[expect(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::as_conversions,
    reason = "Needed for chebyshev calculation"
)]
#[inline]
pub const fn delta_from_ref(raw: u16) -> i32 {
    let raw_f32 = f32::from(raw.clamp(VALID_RAW_MIN, VALID_RAW_MAX));
    let scaled_t = raw_f32.sub(X_MID).mul(X_HALF_RECIP);
    let delta = chebyshev(scaled_t).sub(REF_VAL).mul(256_f32);
    let clamped = delta.clamp(i32::MIN as f32, 2_147_483_500_f32);
    i32::try_from(clamped as i64).unwrap_or(i32::MAX)
}
