use crate::layout::COL;
pub use crate::layout::shared::layout::{MAC_ROW5, ROW0, ROW1, WIN_ROW5};
use rmk::{a, k, types::action::KeyAction};

pub const ROW2: [KeyAction; COL] = [
    k!(Tab),
    k!(Q),
    k!(W),
    k!(E),
    k!(R),
    k!(T),
    k!(Y),
    k!(U),
    k!(I),
    k!(O),
    k!(P),
    k!(LeftBracket),
    k!(RightBracket),
    k!(Backslash),
    k!(Delete),
    k!(End),
    k!(PageDown),
    k!(Kp7),
    k!(Kp8),
    k!(Kp9),
    k!(KpPlus),
];
pub const ROW3: [KeyAction; COL] = [
    k!(CapsLock),
    k!(A),
    k!(S),
    k!(D),
    k!(F),
    k!(G),
    k!(H),
    k!(J),
    k!(K),
    k!(L),
    k!(Semicolon),
    k!(Quote),
    k!(Enter),
    a!(No),
    a!(No),
    a!(No),
    a!(No),
    k!(Kp4),
    k!(Kp5),
    k!(Kp6),
    a!(No),
];
pub const ROW4: [KeyAction; COL] = [
    k!(LShift),
    a!(No),
    k!(Z),
    k!(X),
    k!(C),
    k!(V),
    k!(B),
    k!(N),
    k!(M),
    k!(Comma),
    k!(Dot),
    k!(Slash),
    a!(No),
    k!(RShift),
    a!(No),
    k!(Up),
    a!(No),
    k!(Kp1),
    k!(Kp2),
    k!(Kp3),
    k!(KpEnter),
];
